[package]
name = "nvr-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rtsp-rtp-rs = {path="../rtsp-rtp-rs/"}
onvif-cam-rs = {path="../onvif-cam-rs/"}
anyhow = "1.0.75"
sdl2 = "0.35.2"
log = "0.4.20"
pretty_env_logger = "0.5.0"

[dependencies.tokio]
version = "1"
features = ["full"]
